.TH "ROWS PDF-TO-TEXT" "1" "14-Feb-2019" "0.4.1" "rows pdf-to-text Manual"
.SH NAME
rows\-pdf-to-text \- Extract text from a PDF
.SH SYNOPSIS
.B rows pdf-to-text
[OPTIONS] SOURCE [OUTPUT]
.SH DESCRIPTION
Extract text from a PDF
.SH OPTIONS
.TP
\fB\-\-output\-encoding\fP TEXT
.PP
.TP
\fB\-\-quiet\fP
.PP
.TP
\fB\-\-backend\fP TEXT
.PP
.TP
\fB\-\-pages\fP TEXT
.PP
